language: objective-c
xcode_workspace: DMMSecretaryDemo.xcworkspace
xcode_scheme: DMMSecretaryDemo
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
  - iphonesimulator8.1

script:
  - xctool -workspace DMMSecretaryDemo -scheme DMMSecretaryDemo -configuration Debug -sdk iphonesimulator8.1 clean build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - ./script/coveralls.sh

# before_install:
#   sudo pip install PyYAML; sudo pip install cpp-coveralls
# after_success:
#   ./scripts/coveralls.rb --extension m
