language: objective-c
xcode_workspace: DMMSecretaryDemo.xcworkspace
xcode_scheme: DMMSecretaryDemo
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
  - iphonesimulator8.1

before_install: gem install cocoapods xcpretty slather -N
after_success: slather
