language: objective-c
xcode_workspace: DMMSecretaryDemo.xcworkspace
xcode_scheme: DMMSecretaryDemo
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
  - iphonesimulator8.1
before_install:
  sudo pip install PyYAML; sudo pip install cpp-coveralls
after_success:
  ./scripts/coveralls.rb --extension m --extension mm --exclude-folder include --exclude-folder TestsProject
